create database if not exists blog_db;
use blog_db;
insert into posts (author, title, body, date) values ('Libbi', 'middleware', 'ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas', '2013/11/5');
insert into posts (author, title, body, date) values ('Adina', 'Vision-oriented', 'id nulla ultrices aliquet maecenas leo odio condimentum id luctus', '2017/11/2');
insert into posts (author, title, body, date) values ('Rosalyn', 'intermediate', 'mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero', '2017/1/13');
insert into posts (author, title, body, date) values ('Meara', '3rd generation', 'erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque', '2018/5/14');
insert into posts (author, title, body, date) values ('Sherye', 'support', 'id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum', '2010/5/14');
insert into posts (author, title, body, date) values ('Abey', 'structure', 'convallis eget eleifend luctus ultricies eu nibh quisque id justo sit', '2015/5/14');
insert into posts (author, title, body, date) values ('Mellie', 'project', 'ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam', '2016/5/14');
insert into posts (author, title, body, date) values ('Brett', 'Multi-channelled', 'magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede', '2017/5/14');
insert into posts (author, title, body, date) values ('Hesther', 'object-oriented', 'cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor', '2018/5/14');
insert into posts (author, title, body, date) values ('Hyman', 'product', 'a odio in hac habitasse platea dictumst maecenas ut massa', '2014/5/14');
insert into posts (author, title, body, date) values ('Fleurette', 'implementation', 'vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis', '2020/5/14');
insert into posts (author, title, body, date) values ('Bernetta', 'Robust', 'eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient', '2013/5/14');
insert into posts (author, title, body, date) values ('Hedda', 'User-centric', 'et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus', '2016/5/14');
insert into posts (author, title, body, date) values ('Abbye', 'utilisation', 'nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam', '2014/5/14');
insert into posts (author, title, body, date) values ('Rita', 'discrete', 'velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', '2013/5/14');
insert into posts (author, title, body, date) values ('Paten', 'time-frame', 'felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut', '2020/5/14');
insert into posts (author, title, body, date) values ('Anselm', 'Fundamental', 'vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla', '2017/5/14');
insert into posts (author, title, body, date) values ('Fionnula', 'core', 'ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi', '2015/5/14');
insert into posts (author, title, body, date) values ('Julianna', 'regional', 'semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id', '2015/5/14');
insert into posts (author, title, body, date) values ('Nomi', 'Graphical User Interface', 'turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc', '2013/5/14');
insert into posts (author, title, body, date) values ('Nate', 'needs-based', 'amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus', '2019/5/14');
insert into posts (author, title, body, date) values ('Augustine', 'Monitored', 'primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien', '2010/5/14');
insert into posts (author, title, body, date) values ('Ellerey', 'Self-enabling', 'congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante', '2015/5/14');
insert into posts (author, title, body, date) values ('Othella', 'Proactive', 'potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur', '2012/5/14');
insert into posts (author, title, body, date) values ('Bay', 'scalable', 'luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien', '2016/5/14');
insert into posts (author, title, body, date) values ('Jaime', 'content-based', 'sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante', '2019/5/14');
insert into posts (author, title, body, date) values ('Veronike', 'systematic', 'diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse', '2012/5/14');
insert into posts (author, title, body, date) values ('Gardiner', 'Enhanced', 'morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend', '2017/5/14');
insert into posts (author, title, body, date) values ('Caty', 'even-keeled', 'morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus', '2013/5/14');
insert into posts (author, title, body, date) values ('Ginni', 'policy', 'ipsum aliquam non mauris morbi non lectus aliquam sit amet', '2013/5/14');

select * from posts;